apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld-app
        image: asia.gcr.io/imgdiff-225107/helloworld:latest
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 8080
